version: '3.8'
services:

  # PHP Service
  app:
    build:
      args:
        user: modaui
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: modaui-laragent
    container_name: modaui-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laragent-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: modaui-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laragent-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: modaui-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    networks:
      - laragent-network

networks:
  laragent-network:
    driver: bridge
